# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11

exclude: |
  (?x)^(charts-3rdparty/|
   grafana-plugins
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.json$
      # - id: check-added-large-files
      #- id: check-json
      #  exclude: "charts*/"
      #- id: pretty-format-json
      #  args: ["--autofix", "--no-sort-keys"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--check, --diff, --target-version=py311]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        # language_version: python
        language: system
        # HACK: Force mypy to run on ALL files
        args: ["spotlesssquad"]
        # TODO: add here somehow requirements
        additional_dependencies: []
        # Enable this if you want to see the output even on Success
        verbose: false
        pass_filenames: false
        #files: \.(py)$
        exclude: 'docs'

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
